/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : bigint,
  'name' : string,
  'accountType' : string,
  'amount' : number,
  'riskScore' : bigint,
}
export interface SimulationConfig {
  'timeHorizonYears' : bigint,
  'numSimulations' : bigint,
  'targetValue' : [] | [number],
  'annualContribution' : number,
}
export interface SimulationResult {
  'id' : bigint,
  'totalInitialValue' : number,
  'yearlyStats' : Array<YearStats>,
  'probabilityOfGoal' : number,
  'timestamp' : bigint,
  'config' : SimulationConfig,
  'finalP10' : number,
  'finalP25' : number,
  'finalP50' : number,
  'finalP75' : number,
  'finalP90' : number,
}
export interface YearStats {
  'p10' : number,
  'p25' : number,
  'p50' : number,
  'p75' : number,
  'p90' : number,
  'mean' : number,
  'year' : bigint,
}
export interface _SERVICE {
  'addAccount' : ActorMethod<[string, string, number, bigint], bigint>,
  'clearSimulationHistory' : ActorMethod<[], boolean>,
  'deleteAccount' : ActorMethod<[bigint], boolean>,
  'getAccounts' : ActorMethod<[], Array<Account>>,
  'getSimulationById' : ActorMethod<[bigint], [] | [SimulationResult]>,
  'getSimulationHistory' : ActorMethod<[], Array<SimulationResult>>,
  'saveSimulationResult' : ActorMethod<[SimulationResult], bigint>,
  'updateAccount' : ActorMethod<
    [bigint, string, string, number, bigint],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];