/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Account = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'accountType' : IDL.Text,
  'amount' : IDL.Float64,
  'riskScore' : IDL.Nat,
});
export const YearStats = IDL.Record({
  'p10' : IDL.Float64,
  'p25' : IDL.Float64,
  'p50' : IDL.Float64,
  'p75' : IDL.Float64,
  'p90' : IDL.Float64,
  'mean' : IDL.Float64,
  'year' : IDL.Nat,
});
export const SimulationConfig = IDL.Record({
  'timeHorizonYears' : IDL.Nat,
  'numSimulations' : IDL.Nat,
  'targetValue' : IDL.Opt(IDL.Float64),
  'annualContribution' : IDL.Float64,
});
export const SimulationResult = IDL.Record({
  'id' : IDL.Nat,
  'totalInitialValue' : IDL.Float64,
  'yearlyStats' : IDL.Vec(YearStats),
  'probabilityOfGoal' : IDL.Float64,
  'timestamp' : IDL.Int,
  'config' : SimulationConfig,
  'finalP10' : IDL.Float64,
  'finalP25' : IDL.Float64,
  'finalP50' : IDL.Float64,
  'finalP75' : IDL.Float64,
  'finalP90' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'clearSimulationHistory' : IDL.Func([], [IDL.Bool], []),
  'deleteAccount' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getSimulationById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SimulationResult)],
      ['query'],
    ),
  'getSimulationHistory' : IDL.Func([], [IDL.Vec(SimulationResult)], ['query']),
  'saveSimulationResult' : IDL.Func([SimulationResult], [IDL.Nat], []),
  'updateAccount' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Account = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'accountType' : IDL.Text,
    'amount' : IDL.Float64,
    'riskScore' : IDL.Nat,
  });
  const YearStats = IDL.Record({
    'p10' : IDL.Float64,
    'p25' : IDL.Float64,
    'p50' : IDL.Float64,
    'p75' : IDL.Float64,
    'p90' : IDL.Float64,
    'mean' : IDL.Float64,
    'year' : IDL.Nat,
  });
  const SimulationConfig = IDL.Record({
    'timeHorizonYears' : IDL.Nat,
    'numSimulations' : IDL.Nat,
    'targetValue' : IDL.Opt(IDL.Float64),
    'annualContribution' : IDL.Float64,
  });
  const SimulationResult = IDL.Record({
    'id' : IDL.Nat,
    'totalInitialValue' : IDL.Float64,
    'yearlyStats' : IDL.Vec(YearStats),
    'probabilityOfGoal' : IDL.Float64,
    'timestamp' : IDL.Int,
    'config' : SimulationConfig,
    'finalP10' : IDL.Float64,
    'finalP25' : IDL.Float64,
    'finalP50' : IDL.Float64,
    'finalP75' : IDL.Float64,
    'finalP90' : IDL.Float64,
  });
  
  return IDL.Service({
    'addAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'clearSimulationHistory' : IDL.Func([], [IDL.Bool], []),
    'deleteAccount' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getSimulationById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SimulationResult)],
        ['query'],
      ),
    'getSimulationHistory' : IDL.Func(
        [],
        [IDL.Vec(SimulationResult)],
        ['query'],
      ),
    'saveSimulationResult' : IDL.Func([SimulationResult], [IDL.Nat], []),
    'updateAccount' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };