/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Account {
    id: bigint;
    name: string;
    accountType: string;
    amount: number;
    riskScore: bigint;
}
export interface SimulationResult {
    id: bigint;
    totalInitialValue: number;
    yearlyStats: Array<YearStats>;
    probabilityOfGoal: number;
    timestamp: bigint;
    config: SimulationConfig;
    finalP10: number;
    finalP25: number;
    finalP50: number;
    finalP75: number;
    finalP90: number;
}
export interface YearStats {
    p10: number;
    p25: number;
    p50: number;
    p75: number;
    p90: number;
    mean: number;
    year: bigint;
}
export interface SimulationConfig {
    timeHorizonYears: bigint;
    numSimulations: bigint;
    targetValue?: number;
    annualContribution: number;
}
export interface backendInterface {
    addAccount(name: string, accountType: string, amount: number, riskScore: bigint): Promise<bigint>;
    clearSimulationHistory(): Promise<boolean>;
    deleteAccount(id: bigint): Promise<boolean>;
    getAccounts(): Promise<Array<Account>>;
    getSimulationById(id: bigint): Promise<SimulationResult | null>;
    getSimulationHistory(): Promise<Array<SimulationResult>>;
    saveSimulationResult(result: SimulationResult): Promise<bigint>;
    updateAccount(id: bigint, name: string, accountType: string, amount: number, riskScore: bigint): Promise<boolean>;
}
import type { SimulationConfig as _SimulationConfig, SimulationResult as _SimulationResult, YearStats as _YearStats } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAccount(arg0: string, arg1: string, arg2: number, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAccount(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAccount(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async clearSimulationHistory(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearSimulationHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearSimulationHistory();
            return result;
        }
    }
    async deleteAccount(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount(arg0);
            return result;
        }
    }
    async getAccounts(): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccounts();
            return result;
        }
    }
    async getSimulationById(arg0: bigint): Promise<SimulationResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSimulationById(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSimulationById(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSimulationHistory(): Promise<Array<SimulationResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSimulationHistory();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSimulationHistory();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveSimulationResult(arg0: SimulationResult): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSimulationResult(to_candid_SimulationResult_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSimulationResult(to_candid_SimulationResult_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAccount(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_SimulationConfig_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SimulationConfig): SimulationConfig {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SimulationResult_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SimulationResult): SimulationResult {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SimulationResult]): SimulationResult | null {
    return value.length === 0 ? null : from_candid_SimulationResult_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    totalInitialValue: number;
    yearlyStats: Array<_YearStats>;
    probabilityOfGoal: number;
    timestamp: bigint;
    config: _SimulationConfig;
    finalP10: number;
    finalP25: number;
    finalP50: number;
    finalP75: number;
    finalP90: number;
}): {
    id: bigint;
    totalInitialValue: number;
    yearlyStats: Array<YearStats>;
    probabilityOfGoal: number;
    timestamp: bigint;
    config: SimulationConfig;
    finalP10: number;
    finalP25: number;
    finalP50: number;
    finalP75: number;
    finalP90: number;
} {
    return {
        id: value.id,
        totalInitialValue: value.totalInitialValue,
        yearlyStats: value.yearlyStats,
        probabilityOfGoal: value.probabilityOfGoal,
        timestamp: value.timestamp,
        config: from_candid_SimulationConfig_n4(_uploadFile, _downloadFile, value.config),
        finalP10: value.finalP10,
        finalP25: value.finalP25,
        finalP50: value.finalP50,
        finalP75: value.finalP75,
        finalP90: value.finalP90
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timeHorizonYears: bigint;
    numSimulations: bigint;
    targetValue: [] | [number];
    annualContribution: number;
}): {
    timeHorizonYears: bigint;
    numSimulations: bigint;
    targetValue?: number;
    annualContribution: number;
} {
    return {
        timeHorizonYears: value.timeHorizonYears,
        numSimulations: value.numSimulations,
        targetValue: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.targetValue)),
        annualContribution: value.annualContribution
    };
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SimulationResult>): Array<SimulationResult> {
    return value.map((x)=>from_candid_SimulationResult_n2(_uploadFile, _downloadFile, x));
}
function to_candid_SimulationConfig_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SimulationConfig): _SimulationConfig {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_SimulationResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SimulationResult): _SimulationResult {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timeHorizonYears: bigint;
    numSimulations: bigint;
    targetValue?: number;
    annualContribution: number;
}): {
    timeHorizonYears: bigint;
    numSimulations: bigint;
    targetValue: [] | [number];
    annualContribution: number;
} {
    return {
        timeHorizonYears: value.timeHorizonYears,
        numSimulations: value.numSimulations,
        targetValue: value.targetValue ? candid_some(value.targetValue) : candid_none(),
        annualContribution: value.annualContribution
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    totalInitialValue: number;
    yearlyStats: Array<YearStats>;
    probabilityOfGoal: number;
    timestamp: bigint;
    config: SimulationConfig;
    finalP10: number;
    finalP25: number;
    finalP50: number;
    finalP75: number;
    finalP90: number;
}): {
    id: bigint;
    totalInitialValue: number;
    yearlyStats: Array<_YearStats>;
    probabilityOfGoal: number;
    timestamp: bigint;
    config: _SimulationConfig;
    finalP10: number;
    finalP25: number;
    finalP50: number;
    finalP75: number;
    finalP90: number;
} {
    return {
        id: value.id,
        totalInitialValue: value.totalInitialValue,
        yearlyStats: value.yearlyStats,
        probabilityOfGoal: value.probabilityOfGoal,
        timestamp: value.timestamp,
        config: to_candid_SimulationConfig_n10(_uploadFile, _downloadFile, value.config),
        finalP10: value.finalP10,
        finalP25: value.finalP25,
        finalP50: value.finalP50,
        finalP75: value.finalP75,
        finalP90: value.finalP90
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
